name: CI

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          npm install -g aws-cdk
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Run tests
        run: pytest
      - name: CDK synth
        run: cdk synth --app "python -m codex.infra.app"
        env:
          CDK_NEW_BOOTSTRAP: 1
