name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          npm install -g aws-cdk
      - name: CDK synth
        run: cdk synth --app "python -m codex.infra.app"
        env:
          CDK_NEW_BOOTSTRAP: 1
  deploy:
    needs: synth
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://console.aws.amazon.com/
    steps:
      - name: Await manual approval
        run: echo "Deployments require manual approval via environment protection rules."
      - name: Placeholder deploy step
        run: echo "Invoke 'cdk deploy' from a release runner."
